version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: ./packages/my-app/Dockerfile
    env_file:
      - ./.env
    command: node ./main.js
    ports:
      - 3000:3000
    platform: linux/amd64
    image: a631953720/utils-monorepo-my-app
