// 根據 getStockTable 列出來的表，用來對照 table id
export const stockKeyOptions = [
  { text: '成交價', value: 0 },
  { text: '昨收', value: 1 },
  { text: '漲跌價', value: 2 },
  { text: '漲跌幅', value: 3 },
  { text: '振幅', value: 4 },
  { text: '開盤', value: 5 },
  { text: '最高', value: 6 },
  { text: '最低', value: 7 },
  { text: '成交張數', value: 8 },
  { text: '成交金額', value: 9 },
  { text: '成交筆數', value: 10 },
  { text: '成交均張', value: 11 },
  { text: '成交均價', value: 12 },
  { text: 'PBR', value: 13 },
  { text: 'PER', value: 14 },
  { text: 'PEG', value: 15 },
  { text: '昨日張數', value: 16 },
  { text: '昨日金額', value: 17 },
  { text: '昨日筆數', value: 18 },
  { text: '昨日均張', value: 19 },
  { text: '昨日均價', value: 20 },
  { text: '昨漲跌價 (幅)', value: 21 },
];
